name: 'heart-attack-prod'

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  PROJECT_ID: 'food-delivery-71' 
  REGION: 'europe-west3' 
  SERVICE: 'admin-heart-attack-prod' 

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: Configure Google Cloud Credentials
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker europe-west3-docker.pkg.dev
        shell: bash

      - name: 'Build and Push Container'
        run: |-

          DOCKER_TAG="europe-west3-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: 'europe-west3-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}'

      - name: 'Show output'
        run: |-
          echo ${{ steps.deploy.outputs.url }}
 